# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Latest blog post workflow

on:
  schedule:
    - cron: "0 16 * * *" # 매일 자정 (KST)
  workflow_dispatch: # 수동 실행 버튼 활성화
    

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ksko0424.github.io/index.xml"
          max_post_count: 7
          template: "$newline- [$title]($url) - $date"
          date_format: "mmm dd, yyyy"
